name: Jesse Ukkonen
markdown: kramdown
permalink: /:title
url: https://jesseukkonen.fi
canonical_url: 'jesseukkonen.fi'
type: Person

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: Jesse Ukkonen
tagline: A Designer With an Inclusive Mindset
description: I'm Jesse, a Designer with a curious mind and passion for inclusive design. This is my website, come check it out.

image:
  path: /images/jesse_ukkonen_og-image.jpg
  height: 630
  width: 1200

defaults:
  - scope:
      path: ""
    values:
      image: /images/jesse_ukkonen_og-image.jpg


social:
  links:
    - https://www.linkedin.com/in/jesseukkonen
    - https://www.instagram.com/jesseinen
    - https://github.com/jesseu
