name: Jesse Ukkonen
markdown: kramdown
permalink: /:title
url: https://jesseukkonen.fi
canonical_url: 'jesseukkonen.fi'
type: Person

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: Jesse Ukkonen
tagline: A Designer With an Inclusive Mindset
description: I'm Jesse, a product designer with an emphasis in accessibility and calm design. This is my website, come check it out.

image:
  path: /images/jesse_ukkonen_og-image.jpg

social:
  links:
    - https://www.linkedin.com/in/jesseukkonen
    - https://www.instagram.com/jesseinen
    - https://github.com/jesseu
